@extends('admin.layouts.app')
@section('content')
<main class="container-xxl flex-grow-1 container-p-y">
    <div class="d-flex justify-content-between align-items-center mb-6"><div><h1 class="h3 mb-1">{{ $car->exists ? 'Edit car / model' : 'Add car / model' }}</h1><p class="text-body-secondary mb-0">Variants can be connected to this model later.</p></div><a class="btn btn-outline-secondary" href="{{ route('admin.cars.index') }}">Back to cars</a></div>
    @if($brands->isEmpty())<div class="alert alert-warning">No brands exist yet. @if(Auth::user()->hasPermission('brands.create'))<a href="{{ route('admin.brands.create') }}">Create a brand first.</a>@else Ask an administrator to create a brand.@endif</div>@endif
    <x-auth-validation-errors class="mb-4" :errors="$errors" /><div class="card"><div class="card-body"><form method="POST" action="{{ $car->exists ? route('admin.cars.update',$car) : route('admin.cars.store') }}" enctype="multipart/form-data" class="row g-4">@csrf @if($car->exists)@method('PUT')@endif
        <div class="col-md-6"><label class="form-label" for="brand_id">Brand <span class="text-danger">*</span></label><select class="form-select" id="brand_id" name="brand_id" required><option value="">Select a brand</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((string)old('brand_id',$car->brand_id)===(string)$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label" for="name">Model name <span class="text-danger">*</span></label><input class="form-control" id="name" name="name" value="{{ old('name',$car->name) }}" required maxlength="255"></div>
        <div class="col-12"><label class="form-label" for="short_description">Short description</label><input class="form-control" id="short_description" name="short_description" value="{{ old('short_description',$car->short_description) }}" maxlength="500"></div>
        <div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control" id="description" name="description" rows="4" maxlength="10000">{{ old('description',$car->description) }}</textarea></div>
        <div class="col-md-6"><label class="form-label" for="thumbnail">Thumbnail</label><input class="form-control" id="thumbnail" name="thumbnail" type="file" accept=".jpg,.jpeg,.png,.webp,.svg,image/jpeg,image/png,image/webp,image/svg+xml"><div class="form-text">JPG, PNG, WEBP, or SVG up to 4 MB.</div>@if($car->thumbnail)<img class="mt-3 rounded border" src="{{ \Illuminate\Support\Facades\Storage::disk('car_media')->url($car->thumbnail) }}" alt="{{ $car->name }} thumbnail" style="max-width:220px;max-height:140px">@endif</div>
        <div class="col-md-3"><label class="form-label" for="launch_year">Launch year</label><input class="form-control" id="launch_year" type="number" name="launch_year" value="{{ old('launch_year',$car->launch_year) }}" min="1886" max="{{ now()->year }}"></div><div class="col-md-3"><label class="form-label" for="discontinued_year">Discontinued year</label><input class="form-control" id="discontinued_year" type="number" name="discontinued_year" value="{{ old('discontinued_year',$car->discontinued_year) }}" min="1886" max="{{ now()->year }}"></div>
        <div class="col-md-4"><label class="form-label" for="body_type">Body type</label><select class="form-select" id="body_type" name="body_type"><option value="">Select body type</option>@foreach($bodyTypes as $type)<option value="{{ $type }}" @selected(old('body_type',$car->body_type)===$type)>{{ ucfirst($type) }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label">Fuel types</label>@foreach($fuelTypes as $type)<label class="form-check"><input class="form-check-input" type="checkbox" name="fuel_types[]" value="{{ $type }}" @checked(in_array($type,old('fuel_types',$car->fuel_types ?? []),true))><span class="form-check-label">{{ ucfirst($type) }}</span></label>@endforeach</div>
        <div class="col-md-4"><label class="form-label">Transmission types</label>@foreach($transmissionTypes as $type)<label class="form-check"><input class="form-check-input" type="checkbox" name="transmission_types[]" value="{{ $type }}" @checked(in_array($type,old('transmission_types',$car->transmission_types ?? []),true))><span class="form-check-label">{{ strtoupper($type) }}</span></label>@endforeach</div>
        <div class="col-md-3"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="active" @selected(old('status',$car->status ?: 'active')==='active')>Active</option><option value="inactive" @selected(old('status',$car->status)==='inactive')>Inactive</option></select></div><div class="col-md-3"><label class="form-label" for="sort_order">Sort order</label><input class="form-control" id="sort_order" type="number" name="sort_order" value="{{ old('sort_order',$car->sort_order ?? 0) }}" min="0"></div>
        <div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit" @disabled($brands->isEmpty())>{{ $car->exists ? 'Save changes' : 'Create car / model' }}</button><a class="btn btn-outline-secondary" href="{{ route('admin.cars.index') }}">Cancel</a></div>
    </form></div></div>
</main>
@endsection
