@extends('admin.layouts.app')
@section('content')
<main class="container-xxl flex-grow-1 container-p-y">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-6"><div><h1 class="h3 mb-1">Cars / Models</h1><p class="text-body-secondary mb-0">Manage models belonging to your automotive brands.</p></div>@if(Auth::user()->hasPermission('cars.create'))<a class="btn btn-primary" href="{{ route('admin.cars.create') }}"><i class="bx bx-plus"></i>Add car / model</a>@endif</div>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    <div class="card"><div class="card-body border-bottom"><form method="GET" class="row g-3 align-items-end">
        <div class="col-md-4"><label class="form-label" for="search">Search</label><input class="form-control" id="search" name="search" value="{{ request('search') }}" placeholder="Model name or slug"></div>
        <div class="col-md-3"><label class="form-label" for="brand_id">Brand</label><select class="form-select" id="brand_id" name="brand_id"><option value="">All brands</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((string)request('brand_id') === (string)$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select></div>
        <div class="col-md-3"><label class="form-label" for="body_type">Body type</label><select class="form-select" id="body_type" name="body_type"><option value="">All body types</option>@foreach($bodyTypes as $type)<option value="{{ $type }}" @selected(request('body_type') === $type)>{{ ucfirst($type) }}</option>@endforeach</select></div>
        <div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-outline-secondary" href="{{ route('admin.cars.index') }}">Clear</a></div>
    </form></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Model</th><th>Brand</th><th>Body type</th><th>Launch</th><th>Status</th><th>Sort</th><th>Created</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse($cars as $car)<tr><td><div class="d-flex align-items-center gap-3"><div class="avatar avatar-sm">@if($car->thumbnail)<img class="rounded" src="{{ \Illuminate\Support\Facades\Storage::disk('car_media')->url($car->thumbnail) }}" alt="{{ $car->name }} thumbnail">@else<span class="avatar-initial rounded bg-label-primary">{{ strtoupper(substr($car->name,0,1)) }}</span>@endif</div><span class="fw-semibold">{{ $car->name }}</span></div></td><td>{{ $car->brand->name }}</td><td>{{ $car->body_type ? ucfirst($car->body_type) : '—' }}</td><td>{{ $car->launch_year ?: '—' }}</td><td><span class="badge bg-label-{{ $car->status === 'active' ? 'success' : 'secondary' }}">{{ ucfirst($car->status) }}</span></td><td>{{ $car->sort_order }}</td><td>{{ $car->created_at?->format('d M Y') }}</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-icon btn-outline-secondary" href="{{ route('admin.cars.show',$car) }}" aria-label="View {{ $car->name }}"><i class="bx bx-show"></i></a>@if(Auth::user()->hasPermission('cars.update'))<a class="btn btn-sm btn-icon btn-outline-primary ms-1" href="{{ route('admin.cars.edit',$car) }}" aria-label="Edit {{ $car->name }}"><i class="bx bx-edit"></i></a>@endif @if(Auth::user()->hasPermission('cars.delete'))<form class="d-inline" method="POST" action="{{ route('admin.cars.destroy',$car) }}" onsubmit="return confirm('Delete {{ addslashes($car->name) }}?')">@csrf @method('DELETE')<button class="btn btn-sm btn-icon btn-outline-danger ms-1" aria-label="Delete {{ $car->name }}"><i class="bx bx-trash"></i></button></form>@endif</td></tr>@empty<tr><td colspan="8" class="text-center py-6"><h2 class="h5">No car models found</h2><p class="text-body-secondary mb-0">Try changing your filters or add the first model.</p></td></tr>@endforelse
    </tbody></table></div>@if($cars->hasPages())<div class="card-footer">{{ $cars->links() }}</div>@endif</div>
</main>
@endsection
