@extends('admin.layouts.app')
@section('content')
<main class="container-xxl flex-grow-1 container-p-y">
    <div class="d-flex justify-content-between align-items-center mb-6"><div><h1 class="h3 mb-1">{{ $variant->exists ? 'Edit variant' : 'Add variant' }}</h1><p class="text-body-secondary mb-0">Connect a variant to one car / model.</p></div><a class="btn btn-outline-secondary" href="{{ route('admin.variants.index') }}">Back to variants</a></div>
    @if($brands->isEmpty())<div class="alert alert-warning">No brands exist yet. @if(Auth::user()->hasPermission('brands.create'))<a href="{{ route('admin.brands.create') }}">Create a brand first.</a>@else Ask an administrator to create a brand.@endif</div>@endif
    <x-auth-validation-errors class="mb-4" :errors="$errors" /><div class="card"><div class="card-body"><form method="POST" action="{{ $variant->exists ? route('admin.variants.update',$variant) : route('admin.variants.store') }}" class="row g-4">@csrf @if($variant->exists)@method('PUT')@endif
        <div class="col-md-6"><label class="form-label" for="brand_id">Brand <span class="text-danger">*</span></label><select class="form-select" id="brand_id" name="brand_id" required><option value="">Select a brand</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((string)old('brand_id',$variant->carModel?->brand_id)===(string)$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label" for="car_model_id">Car / Model <span class="text-danger">*</span></label><select class="form-select" id="car_model_id" name="car_model_id" required data-selected="{{ old('car_model_id',$variant->car_model_id) }}"><option value="">Select a model</option>@foreach($models as $model)<option value="{{ $model->id }}" @selected((string)old('car_model_id',$variant->car_model_id)===(string)$model->id)>{{ $model->name }}{{ $model->status === 'inactive' ? ' (Inactive)' : '' }}</option>@endforeach</select><div class="form-text" id="model-status"></div></div>
        <div class="col-md-6"><label class="form-label" for="name">Variant name <span class="text-danger">*</span></label><input class="form-control" id="name" name="name" value="{{ old('name',$variant->name) }}" required maxlength="255" placeholder="SX(O)"></div>
        <div class="col-md-6"><label class="form-label" for="variant_code">Variant code</label><input class="form-control" id="variant_code" name="variant_code" value="{{ old('variant_code',$variant->variant_code) }}" maxlength="100"></div>
        <div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control" id="description" name="description" rows="4" maxlength="10000">{{ old('description',$variant->description) }}</textarea></div>
        <div class="col-md-3"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="active" @selected(old('status',$variant->status ?: 'active')==='active')>Active</option><option value="inactive" @selected(old('status',$variant->status)==='inactive')>Inactive</option></select></div><div class="col-md-3"><label class="form-label" for="sort_order">Sort order</label><input class="form-control" id="sort_order" type="number" name="sort_order" value="{{ old('sort_order',$variant->sort_order ?? 0) }}" min="0"></div>
        <div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit" @disabled($brands->isEmpty())>{{ $variant->exists ? 'Save changes' : 'Create variant' }}</button><a class="btn btn-outline-secondary" href="{{ route('admin.variants.index') }}">Cancel</a></div>
    </form></div></div>
</main>
<script>const brandSelect = document.getElementById('brand_id'); const modelSelect = document.getElementById('car_model_id'); const modelStatus = document.getElementById('model-status'); const modelsUrl = @json(route('admin.variants.models')); async function loadModels() { modelSelect.innerHTML = '<option value="">Loading models...</option>'; modelSelect.disabled = true; modelStatus.textContent = ''; if (!brandSelect.value) { modelSelect.innerHTML = '<option value="">Select a brand first</option>'; modelSelect.disabled = false; return; } try { const response = await fetch(modelsUrl + '?brand_id=' + encodeURIComponent(brandSelect.value), { headers: { Accept: 'application/json' } }); const payload = await response.json(); modelSelect.innerHTML = '<option value="">Select a model</option>'; payload.data.forEach(model => { const option = new Option(model.name + (model.status === 'inactive' ? ' (Inactive)' : ''), model.id); if (String(model.id) === modelSelect.dataset.selected) option.selected = true; modelSelect.add(option); }); if (!payload.data.length) modelStatus.textContent = 'No models exist for this brand.'; } catch (error) { modelSelect.innerHTML = '<option value="">Unable to load models</option>'; modelStatus.textContent = 'Please try again.'; } finally { modelSelect.disabled = false; } } brandSelect.addEventListener('change', () => { modelSelect.dataset.selected = ''; loadModels(); }); if (brandSelect.value) loadModels();</script>
@endsection