@extends('admin.layouts.app')
@section('content')
<main class="container-xxl flex-grow-1 container-p-y">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-6"><div><h1 class="h3 mb-1">Variants</h1><p class="text-body-secondary mb-0">Manage trims belonging to car models.</p></div>@if(Auth::user()->hasPermission('variants.create'))<a class="btn btn-primary" href="{{ route('admin.variants.create') }}"><i class="bx bx-plus me-1"></i>Add variant</a>@endif</div>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    <div class="card"><div class="card-body border-bottom"><form method="GET" action="{{ route('admin.variants.index') }}" class="row g-3 align-items-end">
        <div class="col-md-3"><label class="form-label" for="search">Search</label><input class="form-control" id="search" name="search" value="{{ request('search') }}" placeholder="Name, code, or slug"></div>
        <div class="col-md-3"><label class="form-label" for="brand_id">Brand</label><select class="form-select" id="brand_id" name="brand_id"><option value="">All brands</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((string)request('brand_id') === (string)$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
        <div class="col-md-3"><label class="form-label" for="car_model_id">Car / Model</label><select class="form-select" id="car_model_id" name="car_model_id"><option value="">All models</option>@foreach($models as $model)<option value="{{ $model->id }}" data-brand="{{ $model->brand_id }}" @selected((string)request('car_model_id') === (string)$model->id)>{{ $model->brand->name }} {{ $model->name }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select></div>
        <div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-outline-secondary" href="{{ route('admin.variants.index') }}">Clear</a></div>
    </form></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Variant</th><th>Code</th><th>Car / Model</th><th>Brand</th><th>Status</th><th>Sort</th><th>Created</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse($variants as $variant)<tr><td><span class="fw-semibold">{{ $variant->name }}</span><div class="small text-body-secondary">{{ $variant->slug }}</div></td><td>{{ $variant->variant_code ?: '—' }}</td><td>{{ $variant->carModel->name }}</td><td>{{ $variant->carModel->brand->name }}</td><td><span class="badge bg-label-{{ $variant->status === 'active' ? 'success' : 'secondary' }}">{{ ucfirst($variant->status) }}</span></td><td>{{ $variant->sort_order }}</td><td>{{ $variant->created_at?->format('d M Y') }}</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-icon btn-outline-secondary" href="{{ route('admin.variants.show',$variant) }}" aria-label="View {{ $variant->full_name }}"><i class="bx bx-show"></i></a>@if(Auth::user()->hasPermission('variants.update'))<a class="btn btn-sm btn-icon btn-outline-primary ms-1" href="{{ route('admin.variants.edit',$variant) }}" aria-label="Edit {{ $variant->full_name }}"><i class="bx bx-edit"></i></a>@endif @if(Auth::user()->hasAnyPermission(['specifications.view', 'specifications.create', 'specifications.update']))<a class="btn btn-sm btn-icon btn-outline-success ms-1" href="{{ route('admin.variant-specifications.index',$variant) }}" aria-label="Manage specifications for {{ $variant->full_name }}"><i class="bx bx-list-check"></i></a>@endif @if(Auth::user()->hasPermission('variants.delete'))<form class="d-inline" method="POST" action="{{ route('admin.variants.destroy',$variant) }}" onsubmit="return confirm('Delete {{ addslashes($variant->full_name) }}?')">@csrf @method('DELETE')<button class="btn btn-sm btn-icon btn-outline-danger ms-1" aria-label="Delete {{ $variant->full_name }}"><i class="bx bx-trash"></i></button></form>@endif</td></tr>@empty<tr><td colspan="8" class="text-center py-6"><h2 class="h5">No variants found</h2><p class="text-body-secondary mb-0">Try changing your filters or add the first variant.</p></td></tr>@endforelse
    </tbody></table></div>@if($variants->hasPages())<div class="card-footer">{{ $variants->links() }}</div>@endif</div>
</main>
<script>document.getElementById('brand_id')?.addEventListener('change', function () { const model = document.getElementById('car_model_id'); [...model.options].forEach(option => { option.hidden = option.value && this.value && option.dataset.brand !== this.value; }); if (model.selectedOptions[0]?.hidden) model.value = ''; }); document.getElementById('brand_id')?.dispatchEvent(new Event('change'));</script>
@endsection